### ISSUE TITLE
Problem with 4Dv17

### ISSUE THREAD

**Issue by DenisJager** [miyako/4d-plugin-barcode#1]
Hi Miyako,
I tried to use your plugin with 4DV17 and got a message on this line :
$pdf417:=PDF417 Text ($text;PDF417 Format SVG;ErrorLevel)

<img width="430" alt="image" src="https://user-images.githubusercontent.com/58189911/69574135-c2d6ff80-0fc7-11ea-8270-912aa6cab275.png">

The error means :
Exe cannot be loaded
Licence or privileges error (Barcode (1.0))

Do you have any idea to have it work with 4D v17 or 18 ?

Best regards

Denis

**Comment by miyako** [comment]
as I put clearly on the readme page

https://github.com/miyako/4d-plugin-barcode

this plugin is deprecated. 

it is 32-bit only and there are alternative choices that does the same thing.

**Comment by miyako** [comment]
for example, you could use 
https://github.com/miyako/4d-plugin-zint
instead

**Comment by DenisJager** [comment]
Ok great !
Thanks Miyako. I'll try.
